# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  client:
    name: Client Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Client

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: Client/package-lock.json
          
      - name: Install Dependencies    
        run: npm ci

      - name: Lint and Format Check
        run: npm run lint && npx prettier --write
        continue-on-error: true

      - name: Run tests
        run: npm test
        continue-on-error: true

  server:
    name: Server Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: server/package-lock.json
            
      - name: Install Dependencies
        run: npm ci
        
      - name: Lint and Format Check
        run: npm run lint && npm run format
        continue-on-error: true

      - name: Run Tests
        run: npm test
        continue-on-error: true
