# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  client:
    name: Client Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Client
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout Code
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install Dependencies    
      - run: npm ci

      - name: Lint and Format Check
      - run: npm run lint && npx prettier --write

      - name: Run tests
      - run: npm test
        continue-on-error: true

  server:
    name: Server Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
            
      - name: Install Dependencies
        run: npm ci
        
      - name: Lint and Format Check
        run: npm run lint && npm run format
        
      - name: Run Tests
        run: npm test
        continue-on-error: true
