name: e2e tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    name: run e2e tests
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install server dependencies
        working-directory: server
        run: npm ci

      - name: Install client dependencies
        working-directory: Client
        run: npm ci

      - name: setup .env file for server
        working-directory: server
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env

      - name: Start server
        working-directory: server
        run: |
          npx prisma migrate dev --name init --preview-feature
          nohup npm run start &
          sleep 5

      - name: Install netcat
        run: |
          sudo apt-get update
          sudo apt-get install -y netcat-openbsd

      - name: Wait for server to start
        run: |
          chmod +x ./wait-for-server.sh
          ./wait-for-server.sh

      - name: Install Playwright Browsers
        working-directory: Client
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: Client
        run: npx playwright test
